import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    ADMIN_EMAIL: z.string().email(),
    ADMIN_PASS: z.string().min(1),
    NX_DAEMON: z.string().min(0),
    POSTGRES_DATABASE: z.string().min(1),
    POSTGRES_HOST: z.string().min(1),
    POSTGRES_PASSWORD: z.string().min(1),
    POSTGRES_PRISMA_URL: z.string().min(1),
    POSTGRES_URL: z.string().min(1),
    POSTGRES_URL_NON_POOLING: z.string().min(1),
    POSTGRES_URL_NO_SSL: z.string().min(1),
    POSTGRES_USER: z.string().min(1),
    TURBO_REMOTE_ONLY: z.string().min(0),
    TURBO_RUN_SUMMARY: z.string().min(0),
    VERCEL: z.string().min(0),
    VERCEL_ENV: z.string().min(0),
    VERCEL_GIT_COMMIT_AUTHOR_LOGIN: z.string().min(0),
    VERCEL_GIT_COMMIT_AUTHOR_NAME: z.string().min(0),
    VERCEL_GIT_COMMIT_MESSAGE: z.string().min(0),
    VERCEL_GIT_COMMIT_REF: z.string().min(0),
    VERCEL_GIT_COMMIT_SHA: z.string().min(0),
    VERCEL_GIT_PREVIOUS_SHA: z.string().min(0),
    VERCEL_GIT_PROVIDER: z.string().min(0),
    VERCEL_GIT_PULL_REQUEST_ID: z.string().min(0),
    VERCEL_GIT_REPO_ID: z.string().min(0),
    VERCEL_GIT_REPO_OWNER: z.string().min(0),
    VERCEL_GIT_REPO_SLUG: z.string().min(0),
    VERCEL_URL: z.string().min(0),
    NEXTAUTH_SECRET:z.string().min(1),
    NEXTAUTH_URL:z.string().min(1),
  },
  runtimeEnv: {
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    ADMIN_PASS: process.env.ADMIN_PASS,
    NX_DAEMON: process.env.NX_DAEMON,
    POSTGRES_DATABASE: process.env.POSTGRES_DATABASE,
    POSTGRES_HOST: process.env.POSTGRES_HOST,
    POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
    POSTGRES_PRISMA_URL: process.env.POSTGRES_PRISMA_URL,
    POSTGRES_URL: process.env.POSTGRES_URL,
    POSTGRES_URL_NON_POOLING: process.env.POSTGRES_URL_NON_POOLING,
    POSTGRES_URL_NO_SSL: process.env.POSTGRES_URL_NO_SSL,
    POSTGRES_USER: process.env.POSTGRES_USER,
    TURBO_REMOTE_ONLY: process.env.TURBO_REMOTE_ONLY,
    TURBO_RUN_SUMMARY: process.env.TURBO_RUN_SUMMARY,
    VERCEL: process.env.VERCEL,
    VERCEL_ENV: process.env.VERCEL_ENV,
    VERCEL_GIT_COMMIT_AUTHOR_LOGIN: process.env.VERCEL_GIT_COMMIT_AUTHOR_LOGIN,
    VERCEL_GIT_COMMIT_AUTHOR_NAME: process.env.VERCEL_GIT_COMMIT_AUTHOR_NAME,
    VERCEL_GIT_COMMIT_MESSAGE: process.env.VERCEL_GIT_COMMIT_MESSAGE,
    VERCEL_GIT_COMMIT_REF: process.env.VERCEL_GIT_COMMIT_REF,
    VERCEL_GIT_COMMIT_SHA: process.env.VERCEL_GIT_COMMIT_SHA,
    VERCEL_GIT_PREVIOUS_SHA: process.env.VERCEL_GIT_PREVIOUS_SHA,
    VERCEL_GIT_PROVIDER: process.env.VERCEL_GIT_PROVIDER,
    VERCEL_GIT_PULL_REQUEST_ID: process.env.VERCEL_GIT_PULL_REQUEST_ID,
    VERCEL_GIT_REPO_ID: process.env.VERCEL_GIT_REPO_ID,
    VERCEL_GIT_REPO_OWNER: process.env.VERCEL_GIT_REPO_OWNER,
    VERCEL_GIT_REPO_SLUG: process.env.VERCEL_GIT_REPO_SLUG,
    VERCEL_URL: process.env.VERCEL_URL,
  },
});
